### ISSUE TITLE
Docker readme.md suggestions

### ISSUE THREAD

**Issue by Vortikai** [liyunfan1223/mod-playerbots#883]
It's already merged so I figured I'd report it here.

For the Docker section, a few notes:

1. It is inadvisable for users to edit the `docker-compose.yml` file directly. I recommend following suit with the main branch and having users create a `docker-compose.override.yml` file in the azerothcore-wotlk root directory with the needed worldserver.conf and playerbot.conf configurations. The `docker compose up -d --build` command uses the docker-compose.yml compose file, but overrides settings listed in the docker-compose.override.yml file.

2. In the docker-compose.override.yml file, playerbot settings can be set following the typical `AC_` prefix formula used by Azerothcore. Parts of my own override.yml is provided as an example, though shouldn't be used in the readme as these are my own personal preferences:

```yml
services:
  ac-worldserver:
    environment:
      AC_PREVENT_AFK_LOGOUT: "1"
      AC_GM_ALLOW_INVITE: "1"
      AC_GM_ALLOW_FRIEND: "1"
      AC_INSTANCE_GM_SUMMON_PLAYER: "1"
      AC_WATER_BREATH_TIMER: "60000"
      AC_RATE_XP_KILL: "1"
      AC_RATE_XP_QUEST: "1"
      AC_RATE_XP_QUEST_DF: "1"
      AC_RATE_XP_EXPLORE: 1"
      AC_RATE_XP_PET: "1"
      AC_RATE_HONOR: "1"
      AC_AI_PLAYERBOT_ENABLED: "1"
      AC_AI_PLAYERBOT_RANDOM_BOT_AUTOLOGIN: "1"
      AC_AI_PLAYERBOT_MIN_RANDOM_BOTS: "500"
      AC_AI_PLAYERBOT_MAX_RANDOM_BOTS: "1000"
      AC_AI_PLAYERBOT_ADD_CLASS_COMMAND: "0"
      AC_AI_PLAYERBOT_ALLOW_PLAYER_BOTS: "1"
      AC_AI_PLAYERBOT_SUMMON_WHEN_GROUP: "0"
      AC_AI_PLAYERBOT_FREE_FOOD: "0"
      AC_AI_PLAYERBOT_REVIVE_BOT_WHEN_SUMMONED: "0"
      AC_AI_PLAYERBOT_SYNC_LEVEL_WITH_PLAYERS: "0"
      AC_AI_PLAYERBOT_DISABLE_DEATH_KNIGHT_LOGIN: "1"
      AC_AI_PLAYERBOT_RANDOM_BOT_FIXED_LEVEL: "1"
      AC_AI_PLAYERBOT_RANDOM_BOT_GROUP_NEARBY: "0"
      AC_AI_PLAYERBOT_ENABLE_BROADCASTS: "0"
      AC_AI_PLAYERBOT_AUTO_PICK_REWARD: "yes"
      AC_AI_PLAYERBOT_DROP_OBSOLETE_QUESTS: "0"
      AC_AI_PLAYERBOT_ENABLE_NEW_RPG_STRATEGY: "1"
    volumes:
      - ./modules:/azerothcore/modules:ro
```
This example shows docker users an easier way to configure their worldserver and module settings using the recommended docker-compose.override.yml file. Some options are the default found in the respective .conf file, some are different. It's easier to work with when they are all in one place, and updating via git pull is easier.

3. This also adds the :ro flag for extra security on the modules volume mountpoint. 
 
Optionally it could be best to describe that security is best set up in an .env file before issuing the `--build` command to change e.g. the database password, as once the ac-database container is created, the default root password is very difficult to change. 

You could also optionally provided support in the form of just saying most issues with docker installations come back to permissions. This might help keep requests for help with docker low.
